# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="if_you_like",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="If you like"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="title_short",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Short title"
            ),
        ),
        migrations.AddField(
            model_name="historicalarticle",
            name="if_you_like",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="If you like"
            ),
        ),
        migrations.AddField(
            model_name="historicalarticle",
            name="title_short",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Short title"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="article",
            name="description",
            field=models.CharField(
                blank=True, max_length=160, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="description",
            field=models.CharField(
                blank=True, max_length=160, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="slug",
            field=models.SlugField(max_length=255, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
    ]
