# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20161217_1906"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
        migrations.AddField(
            model_name="historicalarticle",
            name="image",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
    ]
