# Generated by Django 4.2 on 2025-09-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_historicalarticle_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmazonProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asin", models.CharField(max_length=10, unique=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "image_url_2x",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fetch_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="amazonproduct",
            index=models.Index(fields=["asin"], name="blog_amazon_asin_7897c4_idx"),
        ),
    ]
